### ISSUE TITLE
BUG - Opening Zutilo preferences creates strange menu and hangs Zotero

### ISSUE THREAD

**Issue by mjgreis** [wshanks/Zutilo#181] opened 2021-02-09 20:20 UTC
I've just run into a very odd bug. When I went to open the Zutilo preferences item, this very strange overlay menu appeared.

It looks like a spread-out version of the options screen overlaying the main Zotero menu. There are headers like "Zotero item menu", "About Zutilo". There is no way to close to get back to Zotero, so I have to kill the Zotero task and re-open the application.

I've attached a screenshot.

I am on the latest version of Zotero (5.0.95.1) and Zutilo, running on Windows 10.

![Zotero zutilo error screen shot](https://user-images.githubusercontent.com/26437379/107423453-5112a500-6aea-11eb-9efc-9fd2a6f2316e.jpg)

Thanks for any help you can provide.

**Comment by wshanks** [comment] 2021-02-18 16:16
Hmm, that is unfortunate. I can't reproduce it on my system, but I don't have easy access to a Windows 10 system. I will try to test when I do. I added some labels to the issue in case that helps flag it for someone else who can reproduce and help fix it.

Is this the first time you opened the Zutilo preferences, or did it used to work? It would be helpful to know if this only started happening on a recent version of Zotero. Can you try ZotFile and see if its preference window works properly?

**Comment by mjgreis** [comment] 2021-02-18 18:19
Thanks!  In answer to your questions,

It used to work, though it's been a while since I opened the Zutilo preferences so I can't tell how far back this may go.. 
 I just checked my previous laptop (I migrated last year).  FWIW, that has Zotero 5.0.87 and generates the same error.  

Zotfile's preferences open with no problem.

I can't offer help on the coding side, but happy to do any other testing or troubleshooting that would be helpful.  

(Having Zotero completely freeze, requiring me to kill the Zotero process and restart to proceed may limit how useful that is.)

**Comment by qqobb** [comment] 2021-03-15 01:21
Zutilo generally works well on Windows 10. This should be some issue that is specific to your setup.

This very much looks like https://github.com/wshanks/Zutilo/issues/114. What version of Zutilo are you running? Maybe you can tell from "Tools" -> "Add-ons". In any case, I would recommend downloading the latest version from the [releases page](https://github.com/wshanks/Zutilo/releases). Then, in Zotero's "Add-ons" window, click the gear menu in the top right and install the new XPI file.

If this doesn't help, we could give you more advice. You might, e.g., have some bad preferences that need to be cleared.

**Comment by qqobb** [comment] 2022-01-23 08:02
This issue seems to be resolved in general, so I'm closing it. Please let us know if you're (still) getting it.

**Closed by qqobb** 2022-01-23 08:02 UTC
Labels: help-welcome, windows

**Comment by mjgreis** [comment] 2022-01-23 22:15
I am no longer seeing the problem.  I'm on the latest version of Zutilo (3.10.0).  

Thanks for following up!
